export const shorts = [
    {
        source: {
            id: null,
            name: "BBC News",
        },
        author: {
            name: "John Doe",
            image: "https://picsum.photos/200/501",
            links: [
                { url: "https://linkedin.com/in/john-doe", name: "LinkedIn" },
                { url: "https://whatsapp.com/john-doe", name: "whatsapp" },
                { url: "https://email.com/john-doe", name: "email" },
                { url: "https://instagram.com/john_doe", name: "Instagram" },
                { url: "https://twitter.com/john_doe", name: "Twitter" },
                { url: "https://facebook.com/john.doe", name: "Facebook" },
                { url: "https://youtube.com/johndoe", name: "Youtube" },
            ],
        },
        title: "Breaking News: New scientific breakthrough discovered!",
        description: "A team of scientists has made a groundbreaking discovery that could change the world A team of scientists has made a groundbreaking discovery that could change the world A team of scientists has made a groundbreaking discovery that could change the world A team of scientists has made a groundbreaking discovery that could change the world A team of scientists has made a groundbreaking discovery that could change the world A team of scientists has made a groundbreaking discovery that could change the world A team of scientists has made a groundbreaking discovery that could change the world A team of scientists has made a groundbreaking discovery that could change the world.",
        urlToImage: "https://picsum.photos/1070/580",
        publishedAt: "2023-06-12T10:00:00",
        views: 1500,
        comments: 120,
        subcategory: "trending",
        category: "Science",
        location: 'delhi',
        content: "Scientists have discovered a new element in the periodic table...",
    },
    {
        source: {
            id: null,
            name: "BBC News",
        },
        author: {
            name: "John Doe",
            image: "https://picsum.photos/200/201",
            links: [
                { url: "https://linkedin.com/in/john-doe", name: "LinkedIn" },
                { url: "https://whatsapp.com/john-doe", name: "whatsapp" },
                { url: "https://email.com/john-doe", name: "email" },
                { url: "https://instagram.com/john_doe", name: "Instagram" },
                { url: "https://twitter.com/john_doe", name: "Twitter" },
                { url: "https://facebook.com/john.doe", name: "Facebook" },
                { url: "https://youtube.com/johndoe", name: "Youtube" },
            ],
        },
        title: "Breaking News: New scientific breakthrough discovered!",
        description: "A team of scientists has made a groundbreaking discovery that could change the world.",
        urlToImage: "https://picsum.photos/1070/770",
        publishedAt: "2023-06-12T10:00:00",
        views: 1500,
        comments: 120,
        subcategory: "trending",
        category: "Science",
        location: 'delhi',
        content: "Scientists have discovered a new element in the periodic table...",
    },
    {
        source: {
            id: null,
            name: "BBC News",
        },
        author: {
            name: "John Doe",
            image: "https://picsum.photos/200/310",
            links: [
                { url: "https://linkedin.com/in/john-doe", name: "LinkedIn" },
                { url: "https://whatsapp.com/john-doe", name: "whatsapp" },
                { url: "https://email.com/john-doe", name: "email" },
                { url: "https://instagram.com/john_doe", name: "Instagram" },
                { url: "https://twitter.com/john_doe", name: "Twitter" },
                { url: "https://facebook.com/john.doe", name: "Facebook" },
                { url: "https://youtube.com/johndoe", name: "Youtube" },
            ],
        },
        title: "Breaking News: New scientific breakthrough discovered!",
        description: "A team of scientists has made a groundbreaking discovery that could change the world.",
        urlToImage: "https://picsum.photos/1070/500",
        publishedAt: "2023-06-12T10:00:00",
        views: 1500,
        comments: 120,
        subcategory: "trending",
        category: "Science",
        location: 'delhi',
        content: "Scientists have discovered a new element in the periodic table...",
    },
    {
        source: {
            id: null,
            name: "BBC News",
        },
        author: {
            name: "John Doe",
            image: "https://picsum.photos/200/301",
            links: [
                { url: "https://linkedin.com/in/john-doe", name: "LinkedIn" },
                { url: "https://whatsapp.com/john-doe", name: "whatsapp" },
                { url: "https://email.com/john-doe", name: "email" },
                { url: "https://instagram.com/john_doe", name: "Instagram" },
                { url: "https://twitter.com/john_doe", name: "Twitter" },
                { url: "https://facebook.com/john.doe", name: "Facebook" },
                { url: "https://youtube.com/johndoe", name: "Youtube" },
            ],
        },
        title: "Breaking News: New scientific breakthrough discovered!",
        description: "A team of scientists has made a groundbreaking discovery that could change the world.",
        urlToImage: "https://picsum.photos/1070/570",
        publishedAt: "2023-06-12T10:00:00",
        views: 1500,
        comments: 120,
        subcategory: "trending",
        category: "Science",
        location: 'delhi',
        content: "Scientists have discovered a new element in the periodic table...",
    },
    {
        source: {
            id: null,
            name: "BBC News",
        },
        author: {
            name: "John Doe",
            image: "https://picsum.photos/200/300",
            links: [
                { url: "https://linkedin.com/in/john-doe", name: "LinkedIn" },
                { url: "https://whatsapp.com/john-doe", name: "whatsapp" },
                { url: "https://email.com/john-doe", name: "email" },
                { url: "https://instagram.com/john_doe", name: "Instagram" },
                { url: "https://twitter.com/john_doe", name: "Twitter" },
                { url: "https://facebook.com/john.doe", name: "Facebook" },
                { url: "https://youtube.com/johndoe", name: "Youtube" },
            ],
        },
        title: "Breaking News: New scientific breakthrough discovered!",
        description: "A team of scientists has made a groundbreaking discovery that could change the world.",
        urlToImage: "https://picsum.photos/1070/400",
        publishedAt: "2023-06-12T10:00:00",
        views: 1500,
        comments: 120,
        subcategory: "trending",
        category: "Science",
        location: 'delhi',
        content: "Scientists have discovered a new element in the periodic table...",
    },
    {
        source: {
            id: null,
            name: "BBC News",
        },
        author: {
            name: "John Doe",
            image: "https://picsum.photos/200/100",
            links: [
                { url: "https://linkedin.com/in/john-doe", name: "LinkedIn" },
                { url: "https://whatsapp.com/john-doe", name: "whatsapp" },
                { url: "https://email.com/john-doe", name: "email" },
                { url: "https://instagram.com/john_doe", name: "Instagram" },
                { url: "https://twitter.com/john_doe", name: "Twitter" },
                { url: "https://facebook.com/john.doe", name: "Facebook" },
                { url: "https://youtube.com/johndoe", name: "Youtube" },
            ],
        },
        title: "Breaking News: New scientific breakthrough discovered!",
        description: "A team of scientists has made a groundbreaking discovery that could change the world.",
        urlToImage: "https://picsum.photos/1070/600",
        publishedAt: "2023-06-12T10:00:00",
        views: 1500,
        comments: 120,
        subcategory: "trending",
        category: "Science",
        location: 'delhi',
        content: "Scientists have discovered a new element in the periodic table...",
    },
]